# Numpy

Если вкратце - это библиотека для множества математических операций.

Здесь пробежимся по базовым функциям.

#### Создадим пару последовательностей с помощью функции `arange`:

In [57]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

arg = np.arange(100) # ф-ция arange создает последовательность
print(arg)
arg2 = np.arange(start = -1, stop = 100.5, step = 0.5) # Аргументы. Start дефолтно = 0, stop всегда меньше указанного значения на один шаг.
print(arg2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ -1.   -0.5   0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5
   5.    5.5   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5
  11.   11.5  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5
  17.   17.5  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5
  23.   23.5  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5
  29.   29.5  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5
  35.   35.5  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5
  41.   41.5  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5
  47.   47.5  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5
  53.   53.5  54.   54.5  55.   55.5 

#### Размерности массивов можно менять с помощью функции `reshape`:

In [3]:
arg_resh = arg.reshape(10,10) # Создали квадратную матрицу 10х10
print(arg_resh)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### Так же поддерживается матричное транспонирование:

In [40]:
matrix = np.arange(20).reshape(2,10)
matrix.T # Или через np.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

#### Можно посмотреть размерность массива с помощью `shape` и посмотреть количество осей с помощью `ndim`:

In [4]:
arg_resh.shape

(10, 10)

In [5]:
arg_resh.ndim

2

#### Создадим массив с помощью `array`:

In [6]:
arr = np.array([1,2,3,4,5,6,3,4])
print(arr)

[1 2 3 4 5 6 3 4]


####  Закономерный вопрос: в чем отличие от списков?
#### Массивы `быстрее` и имеют множество функций:

In [7]:
a = range(100_000_000)
b = range(100_000_000)

In [8]:
%%time
for i in range(len(a)):
    a[i]*b[i]

CPU times: total: 14.6 s
Wall time: 14.7 s


In [9]:
%%time
a_arr = np.array(a)
b_arr = np.array(b)

print(a_arr * b_arr)

[         0          1          4 ... 1274919433 1474919428 1674919425]
CPU times: total: 8.67 s
Wall time: 8.66 s


## Функции массивов:

In [13]:
arrf = np.flip(arr) # Разворот одномерного массива 
print(arrf)

[4 3 6 5 4 3 2 1]


In [19]:
arg_resh_rot = np.rot90(arg_resh, k = 2) # Эта функция поворачивает массив на 90 градусов. Коэффициент k - количество поворотов.
print(arg_resh_rot)

[[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]


In [22]:
arr.argmax() # Индекс максимального значения

5

In [28]:
arr.max() # Максимальное значение

6

In [23]:
arr.argmin() # Индекс минимального значения

0

In [29]:
arr.min() # Минимальное значение

1

In [24]:
arr.argsort() # Список индексов 

array([0, 1, 2, 6, 3, 7, 4, 5], dtype=int64)

In [34]:
arr_argwhere = np.argwhere(arr < 3) # Индексы по условию для значений
print(arr_argwhere)

[[0]
 [1]]


In [27]:
arr_unq = np.unique(arr) # Выводит массив из уникальных значений указанного
print(f'Уникальные значения: {arr_unq}')
print(f'Начальные значения: {arr}')

Уникальные значения: [1 2 3 4 5 6]
Начальные значения: [1 2 3 4 5 6 3 4]


In [32]:
arr_sort = np.sort(arr) # Сортирует массив
print(arr_sort)

[1 2 3 3 4 4 5 6]


In [35]:
arr_where = np.where(arr < 4) # Вывод значений по условию
print(arr_where)

(array([0, 1, 2, 3], dtype=int64),)


## Арифметические операции:

In [36]:
arr.sum() # Суммирование всех элементов массива

28

In [41]:
arr + 1 # +1 ко всем значениям

array([2, 3, 4, 4, 5, 5, 6, 7])

In [44]:
arr - 1 # -1

array([0, 1, 2, 2, 3, 3, 4, 5])

In [42]:
arr * 2 # Умножение на 2 каждого элемента

array([ 2,  4,  6,  6,  8,  8, 10, 12])

In [46]:
arr/2 # Деление на 2

array([0.5, 1. , 1.5, 1.5, 2. , 2. , 2.5, 3. ])

In [47]:
arr ** 2 # Возведение всех элементов в степень

array([ 1,  4,  9,  9, 16, 16, 25, 36])

In [50]:
sin = np.sin(arr) # Sin
print(sin)

[ 0.84147098  0.90929743  0.14112001  0.14112001 -0.7568025  -0.7568025
 -0.95892427 -0.2794155 ]


In [51]:
cos = np.cos(arr) # Cos
print(cos)

[ 0.54030231 -0.41614684 -0.9899925  -0.9899925  -0.65364362 -0.65364362
  0.28366219  0.96017029]


In [52]:
tg = np.tan(arr) # Tg
print(tg)

[ 1.55740772 -2.18503986 -0.14254654 -0.14254654  1.15782128  1.15782128
 -3.38051501 -0.29100619]


In [58]:
arcsin = np.arcsin(arr) # Arcsin
print(arcsin)

[1.57079633        nan        nan        nan        nan        nan
        nan        nan]


In [59]:
arcsinh = np.arcsinh(arr) # Arcsinh
print(arcsinh)

[0.88137359 1.44363548 1.81844646 1.81844646 2.09471255 2.09471255
 2.31243834 2.49177985]


In [60]:
arccos = np.arccos(arr) # Arccos
print(arccos)

[ 0. nan nan nan nan nan nan nan]


In [61]:
arccosh = np.arccosh(arr) # Arccosh
print(arccosh)

[0.         1.3169579  1.76274717 1.76274717 2.06343707 2.06343707
 2.29243167 2.47788873]


#### Матричное умножение:

In [49]:
arg_resh2 = np.arange(-99, 1).reshape(10,10)
dot = np.dot(arg_resh, arg_resh2)
print(dot)

[[ -1605  -1560  -1515  -1470  -1425  -1380  -1335  -1290  -1245  -1200]
 [ -7005  -6860  -6715  -6570  -6425  -6280  -6135  -5990  -5845  -5700]
 [-12405 -12160 -11915 -11670 -11425 -11180 -10935 -10690 -10445 -10200]
 [-17805 -17460 -17115 -16770 -16425 -16080 -15735 -15390 -15045 -14700]
 [-23205 -22760 -22315 -21870 -21425 -20980 -20535 -20090 -19645 -19200]
 [-28605 -28060 -27515 -26970 -26425 -25880 -25335 -24790 -24245 -23700]
 [-34005 -33360 -32715 -32070 -31425 -30780 -30135 -29490 -28845 -28200]
 [-39405 -38660 -37915 -37170 -36425 -35680 -34935 -34190 -33445 -32700]
 [-44805 -43960 -43115 -42270 -41425 -40580 -39735 -38890 -38045 -37200]
 [-50205 -49260 -48315 -47370 -46425 -45480 -44535 -43590 -42645 -41700]]


#### Резюмируя: количество арифметических операций стремится к бесконечности

## Специфичные массивы

In [67]:
zeros = np.zeros((5,5)) # Матрица из нулей
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
ones = np.ones((5,5)) # Матррица из единиц
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
ident = np.identity(5) # Единичная матрица
print(ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Обьединение массивов:

In [71]:
np.vstack((arg_resh, np.zeros(arg_resh.shape)))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.

In [76]:
np.hstack((arg_resh, np.zeros(arg_resh.shape)))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.,  0.,  

## Рандом:

In [129]:
np.random.rand(2, 3) # Массив случайных значений

array([[0.70219827, 0.90320616, 0.88138193],
       [0.4057498 , 0.45244662, 0.26707032]])

In [130]:
np.random.normal(2, 1, size=3) # Случайные выборки из Гауссова распределения

array([2.0169049 , 1.48501648, 2.24450929])

In [148]:
np.random.randint(5, 10, size=3) #  3рандомных целых числа от 5 до 10

array([7, 5, 5])