# NumPy Linalg

#### Это модуль состоит из множества функций линейной алгебры

In [3]:
import numpy as np

arr = np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

## Функции:

In [13]:
power = np.linalg.matrix_power(arr, 2) # Возведение матрицы в степень 2
print(power)

[[ 3355  3410  3465  3520  3575  3630  3685  3740  3795  3850]
 [ 7955  8110  8265  8420  8575  8730  8885  9040  9195  9350]
 [12555 12810 13065 13320 13575 13830 14085 14340 14595 14850]
 [17155 17510 17865 18220 18575 18930 19285 19640 19995 20350]
 [21755 22210 22665 23120 23575 24030 24485 24940 25395 25850]
 [26355 26910 27465 28020 28575 29130 29685 30240 30795 31350]
 [30955 31610 32265 32920 33575 34230 34885 35540 36195 36850]
 [35555 36310 37065 37820 38575 39330 40085 40840 41595 42350]
 [40155 41010 41865 42720 43575 44430 45285 46140 46995 47850]
 [44755 45710 46665 47620 48575 49530 50485 51440 52395 53350]]


In [11]:
matrix = np.array([[1.,5.,6.], [2.,7.,9.], [45.,22.,37.]])
inv = np.linalg.inv(matrix) # Обратная матрица
inv

array([[ 0.67777778, -0.58888889,  0.03333333],
       [ 3.67777778, -2.58888889,  0.03333333],
       [-3.01111111,  2.25555556, -0.03333333]])

In [15]:
np.linalg.det(matrix) # Определитель матрицы

89.99999999999976

In [16]:
vec = np.array([[1, 2], [3, 4], [5, 6]])
np.linalg.norm(vec) # Норма вектора

9.539392014169456